### ISSUE TITLE
Explore alternatives to runkit for PHP7

### ISSUE THREAD

**Issue by Matthewrbowker** [enwikipedia-acc/waca#254] opened 2016-03-17 18:58 UTC
Currently, runkit isn't working for PHP7 (See #253).  If runkit isn't upgraded, we need to explore alternatives.  

Filling this here as a tracking task, this is very low priority and can be closed if runkit is upgraded.

**Comment by stwalkerster** [comment] 2020-04-02 10:45
Prod is now PHP7.3, so all builds are failing now.

**Comment by stwalkerster** [comment] 2020-05-01 17:04
runkit7 is a thing, we should move to that.

**Comment by stwalkerster** [comment] 2020-05-01 17:05
actually, gonna close this as a dupe of #262

**Closed by stwalkerster** 2020-05-01 17:05 UTC
Labels: Priority: High, cleanup, newinternal, tracking
