### ISSUE TITLE
Automatically detect if users are identified

### ISSUE THREAD

**Issue by Matthewrbowker** [enwikipedia-acc/waca#240] opened 2016-02-06 20:34 UTC
Currently, we have to wait for a root to mark the user as identified.  Would be helpful to be able to mark them as identified on the user interface.

**Comment by FastLizard4** [comment] 2016-02-07 00:53
Actually, this is intended behavior.  Roots are intentionally the only users authorized to do identification checks, and it should remain this way unless all the roots agree it should be changed.

(That being said, the ability to do it in the GUI would be useful, but it's not exactly high priority, so I'm leaving this open - but it shoudl still be an action only roots are permitted to perform.)

**Comment by FunPika** [comment] 2016-02-07 03:04
Identification is already the second thing (first being OAuth linking, since the lack of that usually implies they don't even have a wiki account) any tool admin should be checking when they look into a prospective new user. 

I don't understand why we can trust tool admins to judge whether or not a user is suitable for ACC access by checking factors such as experience, block logs, etc., but can't trust them to perform the simple check of a name being on the identification noticeboard. In addition the tool admins and mailing list moderators already have the ability to grant IRC and list access respectively, which [as the guide says](https://en.wikipedia.org/wiki/Wikipedia:Request_an_account/Guide#Messages_outside_of_the_interface), are places where personally identifying information may be discussed.

Unless the Foundation itself is taking a hard stance on this issue, I see no logical reason to restrict this to tool roots.

If we are truly concerned about the slim risk that someone will accidentally approve a non-identified user, perhaps integrate an API check [such as this one](https://meta.wikimedia.org/wiki/Special:ApiSandbox#action=query&prop=links&format=json&pltitles=User%3AFunPika&titles=Access%20to%20nonpublic%20information%20policy%2FNoticeboard) as a safeguard (but of course make it clear that it is no substitute to manually checking the noticeboard)?

**Comment by FastLizard4** [comment] 2016-02-07 04:17
> ...Tool admins and mailing list moderators already have the ability to grant IRC and list access respectively, which as the guide says, are places where personally identifying information may be discussed.

Indeed, where they may be *discussed*.  The tool is itself not just a place where such information can be discussed, but is also a repository of such information.

> If we are truly concerned about the slim risk that someone will accidentally approve a non-identified user, perhaps integrate an API check such as this one as a safeguard (but of course make it clear that it is no substitute to manually checking the noticeboard)?

If an automated check is no substitute for manual checks, why bother with the automatic check in the first place?

**Comment by FunPika** [comment] 2016-02-07 04:44
> If an automated check is no substitute for manual checks, why bother with the automatic check in the first place?
If we can think of a system that can with 100% accuracy determine if someone is identified, without getting thrown off by stuff like comments in the noticeboard, renames, or the enwiki account not being SUL'd with Meta, then sure, we could do away with manual checks all together. Main reason I was thinking of it being more of a safeguard/warning than a fully automated check is because I'm still not certain if stuff like the API query I linked to could have false positives/negatives.

**Comment by Matthewrbowker** [comment] 2016-02-08 20:56
@FastLizard4 If the roots are the only ones you want to set this flag, why not give the roots a separate role within the software and allow this functionality using the role?

**Comment by FastLizard4** [comment] 2016-02-08 21:38
@Matthewrbowker ...Isn't that what I said in my first reply?

**Comment by Matthewrbowker** [comment] 2016-02-10 21:52
@FastLizard4 Apologies, I misunderstood.

**Comment by FastLizard4** [comment] 2016-03-11 03:20
This is now merged into the newinternal branch, so this feature will go live when the tool rewrite does.  Which will hopefully be Soon™.

**Closed by FastLizard4** 2016-03-11 03:20 UTC
Labels: feature
