### ISSUE TITLE
Welcomer bot not working

### ISSUE THREAD

**Issue by Matthewrbowker** [enwikipedia-acc/waca#204] opened 2015-12-04 05:16 UTC
Welcomer bot is not welcoming users.

For examples, see numbers 446 to 544 on [my ACC profile](https://accounts.wmflabs.org/statistics.php?page=Users&user=788)

**Comment by stwalkerster** [comment] 2015-12-30 01:13
Duplicate of #141

**Closed by stwalkerster** 2015-12-30 01:13 UTC
