### ISSUE TITLE
Site notice should be manually accessible

### ISSUE THREAD

**Issue by ElHefWiki** [enwikipedia-acc/waca#658] opened 2021-01-06 16:37 UTC
In old world, users could view the site notice anytime through message management (besides the bug where it wasn't dismissable).

In newinternal, once dismissed it can't be seen until it pops up again on its own. Message management is no longer visible to users, and attempting to access it from the log gives a permission error.

There have been times recently when I glanced through the notice when it popped up, dismissed it, and saw later in the log that a change had been made that I hadn't spotted and now couldn't easily see.

**Comment by stwalkerster** [comment] 2021-01-06 17:11
If you clear your cookies (or specifically the "sitenotice" cookie) for the tool, it'll pop up again.

Not the most user-friendly option, but it is a workaround.

**Comment by stwalkerster** [comment] 2021-01-06 17:14
Marked as bug simply due to this seemingly being a regression

**Closed** 2021-02-23 23:21 UTC
