### ISSUE TITLE
Prohibit Duplicate Requests by email

### ISSUE THREAD

**Issue by dqwiki** [enwikipedia-acc/waca#416] opened 2017-02-15 01:41 UTC
Regardless of down the road [[Inbound Mail]] implementation, we are currently wasting a lot of volunteer hours dealing with duplicate requests by email. This possibly was removed in the first place was due to different name requests showing up on the list.

That has a much simpler way of being resolved than the lazy method of just removing the email requirement. A quick page to change the name of their open request, with a link in their confirmation email would be the easiest way to implement that.

If people don't like that, there could always be a way to cancel a request, again, link in the confirmation email.

Either way though, we need to stop wasting volunteer hours with duplicate requests as much as possible.

**Comment by stwalkerster** [comment] 2017-02-15 13:24
Where do you feel the time is wasted here? The system currently will highlight other requests from this email address, making it immediately obvious that there is another request within the tool.

There's several issues with the proposed solutions - 
a) some people will have deleted the email without thinking about it
b) a lot of people don't read things and won't see any links
c) depending on where the request is rejected, it's either a leak that an account has submitted a request or really sucky UX
d) how do you factor email confirmation into this?
 - do you check confirmed-only open requests? This is great for the case where a user has deleted the wrong email and remade the request with the same details, but falls over then they submit two then confirm two
 - do you only check open requests ignoring confirmation status? This works great for most cases, but falls over when the user deletes the wrong mail or a mail gets lost somewhere for non-address-related reasons
- do you do the check at confirmation time, which fails in the case of a mistake or change-of-mind and the user confirms the wrong request, or we have to leak an account name to an unknown email address

Remember that we are supposed to be the people who handle exceptions where automated systems have failed, so validation of incoming requests should allow for the problems, and we should be passing this to humans as much as possible, with limited automatic processing.

**Comment by stwalkerster** [comment] 2017-02-15 13:36
Basically, any of these options (pretty much with the exception of re-implementing the validation check, which is probably the most sucky of the options) - I'm not willing to do in master. If someone else wants to do it, I'm happy for them to do so on the condition it's also done in newinternal, and is done in a way that doesn't introduce merge conflicts (ie: `git merge --strategy=ours` and ensure everything is working properly in both branches. This means it is slightly more than double the work you might estimate it to be.

**Comment by FastLizard4** [comment] 2017-02-16 21:57
I agree with @stwalkerster in that I really don't see how duplicate requests from an email address is really a "time waster".  For the reasons mentioned, I would be against any automatic rejection of requests with duplicate emails, and I think how things are currently is fine.  If we must implement duplicate email checking, I would at most support a confirmation prompt at time of email verification checking for other email-verified requests - something along the lines of "you have already submitted a request for an account with the name *$USERNAME* - are you sure you wish to submit a new request?", perhaps with a link to the sockpuppetry policy - but even in this case, I feel the problem is better addressed by a human than an automated system, even if only because humans are likely to ignore any automated prompts and proceed anyway.

**Comment by Technical-13** [comment] 2017-02-16 23:11
I've never felt it was a waste of time either, and another example of a valid second request from an email address would be where the person was requesting a name be created for them for an approved bot account.

**Comment by dqwiki** [comment] 2017-02-18 23:25
I wasn't as clear as I should have been in my original bug filling. This should be to prevent submission of multiple requests for **_open_** tickets only. Maybe this just needs to be a change in our backend handling so CUs don't see it if volunteers are perfectly fine dealing with the duplication. For me, my time, and any checkuser's time is extremely valuable. Having multiple open requests in the checkuser queue from the same email only inflates the queue unnecessarily and adds processing time for us, with no additional useful information. It happened with 191493 and 193433.

> so validation of incoming requests should allow for the problems, and we should be passing this to humans as much as possible, with limited automatic processing.

If this is the true goal, then this really isn't a bug, more a backend policy change that needs to happen.

**Comment by stwalkerster** [comment] 2017-02-18 23:31
What I'd suggest in that case is we make a policy change such that if multiple requests do come in from the same email **and** checkuser attention is required, then one is picked to go to the CU queue, the rest go to on-hold?

**Comment by FastLizard4** [comment] 2017-02-19 04:56
Yeah, agree with @stwalkerster - this sounds like a policy problem, not a technical problem that is suitable to be solved by changes to the tool.

**Comment by stwalkerster** [comment] 2017-06-13 20:05
@FastLizard4 / @dqwiki - did we make any policy change regarding this? 

If so, please can we close this; if not, please can we close this after deciding if this is still relevant (and implementing)?

Muchas gracias!

**Comment by FastLizard4** [comment] 2017-06-13 22:50
@stwalkerster as far as I know, no policy changes were made as a result of this, but if @dqwiki is okay with it I can write that into the Guide fairly easily; I still think this isn't something we should prevent through technical measures, though.

**Comment by stwalkerster** [comment] 2020-06-27 09:51
Closing to be handled as a policy issue

**Closed by stwalkerster** 2020-06-27 09:51 UTC
Labels: actually quite difficult
