### ISSUE TITLE
Resolve all issues produced by scrutinizer.ci

### ISSUE THREAD

**Issue by Matthewrbowker** [enwikipedia-acc/waca#236] opened 2016-02-04 22:55 UTC
See https://scrutinizer-ci.com/g/enwikipedia-acc/waca/issues

**Comment by Matthewrbowker** [comment] 2016-04-04 21:20
For #232 see https://scrutinizer-ci.com/g/stwalkerster/waca/issues/newinternal

**Comment by stwalkerster** [comment] 2017-06-13 19:56
Gonna close this as a duplicate of #210

**Closed by stwalkerster** 2017-06-13 19:56 UTC
Labels: actually quite difficult, cleanup, newinternal, performance
