### ISSUE TITLE
[#166590] Check if user has already email-confirmed (Improve)

### ISSUE THREAD

**Issue by RileyHuntley** [enwikipedia-acc/waca#255] opened 2016-03-18 05:12 UTC
Code already checks if user has email confirmed, however, in this case it allowed the requester to email-confirm three times.
Relevant request: https://accounts.wmflabs.org/acc.php?action=zoom&id=166590
`[Community]	email-confirmed	42 minutes ago`
`[Community]	email-confirmed	42 minutes ago`	
`[Community]	email-confirmed	42 minutes ago`

**Comment by FastLizard4** [comment] 2016-03-18 07:48
Pegging this for newinternal since it's low priority and sounds like something that would be easier to do there.  Sorry Simon.  :P Ping #232

**Comment by stwalkerster** [comment] 2016-03-18 11:35
possibe race condition here?

**Comment by FastLizard4** [comment] 2016-03-18 23:01
@stwalkerster How do you mean?

**Comment by stwalkerster** [comment] 2016-03-19 02:56
The check already exists, yet it failed to fire in this case. The likely answer is the check succeeded on all three requests before all three of them marked it as email confirmed, then all three sent the IRC notifications and made the log entries - a standard race condition.

My theory is backed up by the fact that all three log entries occurred at the same second. Unfortunately, I believe MySQL discards fractional seconds on storage.

![image](https://cloud.githubusercontent.com/assets/722710/13896192/9a2251e2-ed7b-11e5-91e8-7afd19ba755e.png)

**Comment by FastLizard4** [comment] 2016-03-19 04:36
Hmm.  It doesn't sound like this would be terribly easy to solve, unless your optimistic locking would also cover this.

**Comment by stwalkerster** [comment] 2016-03-19 12:45
It should, yeah, but it may introduce the problem of errors being thrown instead. I'm fairly sure I've already handled that case, but I'm gonna leave this open for now as a reminder to check it.

**Closed** 2016-04-05 23:29 UTC
Labels: bug, newinternal, Priority: Low
